spring:
  application:
    name: ContentStream
  profiles:
    active: dev # Default active profile

  datasource:
    url: jdbc:mysql://localhost:3307/content_metadata
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

---
spring:
  config:
    activate:
      on-profile: dev # Profile-specific configuration for "dev"
cloud:
  minio:
    endpoint: ${MINIO_ENDPOINT}
    access-key: ${MINIO_ACCESS}
    secret-key: ${MINIO_SECRET}

---
spring:
  config:
    activate:
      on-profile: prod # Profile-specific configuration for "prod"
cloud:
  aws:
    s3:
      bucketName: ${AWS_BUCKET_NAME}
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}